In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
print(torch.cuda.is_available())
print(torch.version.cuda)

True
12.6


CreatingTensor

In [ ]:
# using empty
a= torch.empty(2,3)
print(a)

tensor([[1.0635e-15, 0.0000e+00, 1.8208e-15],
        [0.0000e+00, 1.0809e-15, 0.0000e+00]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.7442, 0.7029, 0.3125],
        [0.9361, 0.9531, 0.1798]])

In [ ]:
#  use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arang" ,torch.arange(0,18,2))
#linspace
print("using linspace" ,torch.linspace(0,18,5))
# using eye
print("using eye" ,torch.eye(5))
# using full
print("using full" ,torch.full((2,3),3))

using arang tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])
using linspace tensor([ 0.0000,  4.5000,  9.0000, 13.5000, 18.0000])
using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full tensor([[3, 3, 3],
        [3, 3, 3]])


Tensor Shapes

In [ ]:
import torch
# print(torch.__version__)
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[139076343471504,       683686496,       684046432],
        [      617339984,               0,       684045056]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

Tensors Data types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.dtype

torch.int64

In [ ]:
# using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [ ]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

Mathematical operation

In [ ]:
# Scalar operation
x=torch.rand(2,2)
x

tensor([[0.8854, 0.5739],
        [0.2666, 0.6274]])

In [ ]:
# add
x+2
# sub
x-2
# mul
x*2
# div
x/3
# int divivision
(x*100)//3
# mod
((x*100)//3)%2

# exp
x**2

tensor([[0.7840, 0.3294],
        [0.0711, 0.3937]])

Element Wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.2696, 0.4414, 0.2969],
        [0.8317, 0.1053, 0.2695]])
tensor([[0.3588, 0.1994, 0.5472],
        [0.0062, 0.9516, 0.0753]])


In [ ]:
# add
a+b
# sub
a-b
# mul
a*b
# div
a/b
# int divivision
(a*100)//b
# power
a**b
# mod
a%b


tensor([[2.6963e-01, 4.2636e-02, 2.9692e-01],
        [2.6345e-05, 1.0531e-01, 4.3697e-02]])

In [ ]:
c=torch.tensor([1,2,3,4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# neg
torch.neg(c)

tensor([-1, -2, -3, -4])

In [ ]:
d=torch.tensor([1.0,2.9,3.0,4.3])

In [ ]:
# round
torch.round(d)

tensor([1., 3., 3., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([1., 3., 3., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.9000, 3.0000, 3.0000])

Reduction operation

In [ ]:
e=torch.randint(size=(2,3),high=10,low=0,dtype=torch.float32)
f=torch.randint(size=(2,3),high=10,low=0,dtype=torch.float32)
e

tensor([[2., 0., 6.],
        [2., 7., 9.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns

torch.sum(e,dim=0)

# sum along rows

torch.sum(e,dim=1)

tensor([17, 19])

In [ ]:
# mean
torch.mean(e)
#mean along col
torch.mean(e,dim=0)
#mean along row
torch.mean(e,dim=1)

tensor([2.6667, 6.0000])

In [ ]:
# median
torch.median(e)
#max and min
torch.max(e)
torch.min(e)
# product
torch.prod(e)
# standard deviation
torch.std(e)
# variance
torch.var(e)
# argmax
torch.argmax(e)
# argmin
torch.argmin(e)

tensor(1)

In [ ]:
f=torch.randint(size=(2,3),high=10,low=0,dtype=torch.float32)
g=torch.randint(size=(3,2),high=10,low=0,dtype=torch.float32)
f
g

tensor([[1., 1.],
        [7., 9.],
        [4., 3.]])

In [ ]:
# matrix mul
torch.matmul(f,g)

tensor([[ 0.,  0.],
        [22., 28.]])

In [ ]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])
# dot product
torch.dot(vec1,vec2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0,1)

tensor([[0., 1.],
        [0., 3.],
        [0., 0.]])

In [ ]:
h=torch.randint(size=(3,3),high=10,low=0,dtype=torch.float32)
h

tensor([[4., 1., 6.],
        [3., 2., 0.],
        [9., 8., 5.]])

In [ ]:
# determinant
torch.det(h)

tensor(61.)

In [ ]:
#inverse
torch.inverse(h)

tensor([[ 0.1639,  0.7049, -0.1967],
        [-0.2459, -0.5574,  0.2951],
        [ 0.0984, -0.3770,  0.0820]])

Comparison operator

In [ ]:
i=torch.randint(size=(2,3),high=10,low=0,dtype=torch.float32)
j=torch.randint(size=(2,3),high=10,low=0,dtype=torch.float32)
print(i)
print(j)

tensor([[3., 7., 5.],
        [7., 1., 5.]])
tensor([[7., 5., 8.],
        [5., 4., 1.]])


In [ ]:
# ghreater than

i>j
#less than
i<j
# equal to
i==j
# not equal to
i!=j
# greter than or equal to
i>=j
# less than or equal to
i<=j


tensor([[ True, False,  True],
        [False,  True, False]])

Special function

In [ ]:
k=torch.randint(size=(2,3), low=0 , high=10,dtype=torch.float32)

In [ ]:
# log
torch.log(k)


tensor([[0.0000,   -inf, 2.1972],
        [  -inf, 2.1972, 0.0000]])

In [ ]:
# exp
torch.exp(k)


tensor([[2.7183e+00, 1.0000e+00, 8.1031e+03],
        [1.0000e+00, 8.1031e+03, 2.7183e+00]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1., 0., 3.],
        [0., 3., 1.]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.5000, 0.9999],
        [0.5000, 0.9999, 0.7311]])

In [ ]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.7311, 0.9526, 0.9975],
        [0.2689, 0.0474, 0.0025]])

In [ ]:
# relu
torch.relu(k)

tensor([[8., 9., 6.],
        [7., 6., 0.]])

Inplace Operations

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.0029, 0.6431, 0.3908],
        [0.6947, 0.0897, 0.8712]])
tensor([[0.1330, 0.4137, 0.6044],
        [0.7581, 0.9037, 0.9555]])


In [ ]:
m+n

tensor([[0.1359, 1.0567, 0.9952],
        [1.4528, 0.9933, 1.8267]])

In [ ]:
m.add_(n)

tensor([[0.1359, 1.0567, 0.9952],
        [1.4528, 0.9933, 1.8267]])

In [ ]:
torch.relu(m)

tensor([[0.1359, 1.0567, 0.9952],
        [1.4528, 0.9933, 1.8267]])

In [ ]:
m.relu_()

tensor([[0.1359, 1.0567, 0.9952],
        [1.4528, 0.9933, 1.8267]])

In [ ]:
m

tensor([[0.1359, 1.0567, 0.9952],
        [1.4528, 0.9933, 1.8267]])

copy a tensor

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.1330, 0.7672, 0.6757],
        [0.6625, 0.2297, 0.9545]])

In [ ]:
b=a.clone()

In [ ]:
id(a)

139071149804352

In [ ]:
id(b)

139071131548592

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating a new tensor in GPU

torch.rand(2,3).to(device)

tensor([[0.6099, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709]], device='cuda:0')

In [ ]:
# Moving a existing tensor in GPU
a

tensor([[0.1330, 0.7672, 0.6757],
        [0.6625, 0.2297, 0.9545]])

In [ ]:
b=a.to(device)

In [ ]:
b+5

tensor([[5.1330, 5.7672, 5.6757],
        [5.6625, 5.2297, 5.9545]], device='cuda:0')

In [ ]:
import torch
import time

# define te size of the matrices
size=10000 #large size for performance comparison

# create random matrices on CPU
mat_cpu1=torch.randn(size , size)
mat_cpu2=torch.randn(size , size)

# Measure time on cpu
start_time=time.time()
result_cpu=torch.matmul(mat_cpu1 , mat_cpu2)
cpu_time = time.time() - start_time

print(f"CPU time: {cpu_time:.4f} sec")

# Move matric to GPU
mat_gpu1=mat_cpu1.to('cuda')
mat_gpu2=mat_cpu2.to('cuda')


# Measure time on GPU

start_time=time.time()
result_gpu=torch.matmul(mat_gpu1 , mat_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"GPU time: {gpu_time:.4f} sec")

# compare

print("speedup (CPU time / GPU time): ", cpu_time/gpu_time)

CPU time: 26.2644 sec
GPU time: 0.7097 sec
speedup (CPU time / GPU time):  37.00545973208245


Reshaping tensor

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.1079, 0.9992, 0.6995, 0.0907],
         [0.2254, 0.9422, 0.6712, 0.2694],
         [0.7156, 0.5338, 0.3207, 0.4728]],

        [[0.4944, 0.9037, 0.1067, 0.2480],
         [0.7951, 0.7574, 0.0755, 0.2409],
         [0.5354, 0.6720, 0.3556, 0.7780]]])

In [ ]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
c=torch.rand(226,226,3)  #image size
c
torch.unsqueeze(c,2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
# squeeze
d=torch.rand(1,20)
d
torch.squeeze(d,0).shape


torch.Size([20])

numpy and pytorch

we can convert numpy arrays to pytorch and pytorch to numy array easily

> Add blockquote



In [ ]:
import numpy as np


In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
type(a)

torch.Tensor

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
type(c)

numpy.ndarray

In [ ]:
d=torch.from_numpy(c)
d

tensor([1, 2, 3])

In [ ]:
type(d)

torch.Tensor